
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: vprodbsc
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  zones: us-west-2a
  fsType: ext4
allowVolumeExpansion: true

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vprodbpvc
spec:
  storageClassName: vprodbsc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
