---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standardformem
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  zone : us-west-2a
reclaimPolicy: Retain
allowVolumeExpansion: true
mountOptions:
  - debug
volumeBindingMode: Immediate

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vprocachevc
  labels:
    app: vprocache
    version: "2.0"
spec:
  storageClassName: standardformem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi